// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE7j7Ph5A3xpTJDGaudSqkN2RXqMscjgQ',
    appId: '1:276240248060:web:cc6980cac131d13d7efb79',
    messagingSenderId: '276240248060',
    projectId: 'photo-sharing-d7aee',
    authDomain: 'photo-sharing-d7aee.firebaseapp.com',
    storageBucket: 'photo-sharing-d7aee.firebasestorage.app',
    measurementId: 'G-FBL8LX9QT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRejaB5nZSP3I3SrPdGdaHlWO4OKgIQqw',
    appId: '1:276240248060:android:d66361bfb1d2b5ce7efb79',
    messagingSenderId: '276240248060',
    projectId: 'photo-sharing-d7aee',
    storageBucket: 'photo-sharing-d7aee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3k9uiCvBlE6BCdst_2VZAnqFN0p18aKY',
    appId: '1:276240248060:ios:a7131346327af4737efb79',
    messagingSenderId: '276240248060',
    projectId: 'photo-sharing-d7aee',
    storageBucket: 'photo-sharing-d7aee.firebasestorage.app',
    iosBundleId: 'com.example.photoSharingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3k9uiCvBlE6BCdst_2VZAnqFN0p18aKY',
    appId: '1:276240248060:ios:a7131346327af4737efb79',
    messagingSenderId: '276240248060',
    projectId: 'photo-sharing-d7aee',
    storageBucket: 'photo-sharing-d7aee.firebasestorage.app',
    iosBundleId: 'com.example.photoSharingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE7j7Ph5A3xpTJDGaudSqkN2RXqMscjgQ',
    appId: '1:276240248060:web:01357e8ef61f3cb67efb79',
    messagingSenderId: '276240248060',
    projectId: 'photo-sharing-d7aee',
    authDomain: 'photo-sharing-d7aee.firebaseapp.com',
    storageBucket: 'photo-sharing-d7aee.firebasestorage.app',
    measurementId: 'G-WLT23N6CRT',
  );
}
